name: forestvpn_api
version: 2.8.11
description: A package to interact api.forestvpn.com (manage vpn profiles
homepage: https://forestvpn.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: '>=4.0.0 <5.0.0'
  built_value: '>=8.1.0 <9.0.0'
  built_collection: '>=5.1.0 <6.0.0'
  build_runner: ^2.1.10

dev_dependencies:
  built_value_generator: '>=8.1.0 <9.0.0'
  test: '>=1.16.0 <1.17.0'
